language: python
python:
  - "3.6"

# email notification
notifications:
  email:
    recipients:
      - 23249735@qq.com
    on_success: never # default: change
    on_failure: never # default: always

# services
services:
  - mongodb

# command to install dependencies
install:
  - grep -Ev '^#' requirements.txt | awk -F'# ' '{print $1}' | xargs -n 1 -L 1 pip install

# command to run tests
before_script:
  - coverage erase
script:
  - nosetests --with-coverage --cover-package backtradercn

after_success:
  - codecov
